### get all users
GET http://localhost:5089/api/user

### login
POST http://localhost:5089/api/login
Content-Type: application/json

{
    "email": "newemail@gmail.com",
    "password": "SecurePassword123"
}

### Register a user 
POST http://localhost:5089/api/register
Content-Type: application/json

{
    "name": "name",
    "email": "newsemail@gmail.com",
    "password": "SecusrePassword123"
}

### Get all products, not implemented yet
GET http://localhost:5089/api/product

### get a product by id
GET http://localhost:5089/api/product/1

### create a product
POST http://localhost:5089/api/product
Content-Type: application/json

{
    "name": "Sneakers",
    "price": 35.33
}

### delete a product by id
DELETE  http://localhost:5089/api/product/1