### Get a list of our supported ciybries
GET http://localhost:5089/api/carriers
X-API-KEY: xskLEaNQdMwXMj2PEqLBhcpUSL3VlrfQBPkoG5WQGANhUGmUO8WVlMyxfF30V2YMm2kwe4Dw9p1TLgrjvVUSTI4UTjzMFlDrrsi2sYAcDAe5BXvmzXonHsIYaetj4JCy

### create a carrier
POST  http://localhost:5089/api/carriers
X-API-KEY: xskLEaNQdMwXMj2PEqLBhcpUSL3VlrfQBPkoG5WQGANhUGmUO8WVlMyxfF30V2YMm2kwe4Dw9p1TLgrjvVUSTI4UTjzMFlDrrsi2sYAcDAe5BXvmzXonHsIYaetj4JCy
Content-Type: application/json

{
  "name": "UPS",
  "code": "UPS",
  "tracingUrl": "https://www.ups.com/track?loc=en_US&tracknum={tracking_number}",
  "supportsTracking": "1",
  "supportInternational": "1",
  "isActive": "1"
}


### delete a carrier by id
DELETE http://localhost:5089/api/carriers/1
X-API-KEY: xskLEaNQdMwXMj2PEqLBhcpUSL3VlrfQBPkoG5WQGANhUGmUO8WVlMyxfF30V2YMm2kwe4Dw9p1TLgrjvVUSTI4UTjzMFlDrrsi2sYAcDAe5BXvmzXonHsIYaetj4JCy

