### check the current identity
GET http://localhost:5089/api/user/whoami
X_API_KEY: sNGWOhCFmrucB1dwsEl39kyWxhLCgRGk9QdB0ancd2l4CAnQpgdZy1UzcPVuQT4Z2j3ljaja8znyIMRHiy9mWY6xyDtBOk74l9nk7hzESwVuj5iunYXBBk5JpVyi4cLc
